name: Continuous Integration #name：ワークフローの名前。Actionsタブを開いた時に表示される。省略した時は代わりにファイルへの相対パスがワークフロー名となる。
on: push #on：<必須>ワークフローを実行するイベント名。pushはプッシュのたびにワークフローを実行させる。イベントは配列形式にして複数指定もできる。

jobs: #jobs：<必須>ジョブの定義の開始を示す。
  unit-test: #unit-test：ジョブのID。jobsのキーとしてユニークであれば任意の文字列でOK。ただし、使える文字列はアルファベット、数字、-、_のみ。
    name: Unit Test #name：ジョブの名前を定義。Actionsタブを開いた時に表示される。省略するとジョブのIDが表示される。
    runs-on: ubuntu-latest #runs-on：<必須>ジョブが実行されるマシンを定義。
    steps: #steps：<必須>ジョブが実行するステップの定義。
      - name: Checkout #name：ステップの名前を定義。ブラウザ上で表示され、省略した時はステップで実行するコマンドが表示される。
        uses: actions/checkout@v2 #uses：アクションの実行を定義。@以降のバージョン指定は必須。
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with: #with：アクションのパラメータを定義。
          node-version: 16.x
      - name: Install dependencies
        run: npm ci #run：コマンドラインの実行を定義。
      - name: Test
        run: npm test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
