name: GitHub Actions Demo

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "挨拶"
        run: echo "Nice to meet you!!"
      - name: "自己紹介"
        run: echo "My Name is Taro!!"
      - name: "趣味"
        run: echo "I love programming!!"
